[32m2023-10-09 15:02:03 +0200[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - b22e2bad-0f9c-46de-8217-1275baf4acae - 468253 - LOGS_CAPTURED - Started capturing logs in process (pid: 468253).
[32m2023-10-09 15:02:03 +0200[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - b22e2bad-0f9c-46de-8217-1275baf4acae - 468253 - upload_info - STEP_START - Started execution of step "upload_info".
[32m2023-10-09 15:02:03 +0200[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - b22e2bad-0f9c-46de-8217-1275baf4acae - 468253 - upload_info - STEP_FAILURE - Execution of step "upload_info" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "upload_info"::

FileNotFoundError: [Errno 2] No such file or directory: '/home/chris/code/affinitypropagation/data/data/info_merged_reduced.csv'

Stack Trace:
  File "/home/chris/.pyenv/versions/3.11.4/lib/python3.11/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/home/chris/.pyenv/versions/3.11.4/lib/python3.11/site-packages/dagster/_utils/__init__.py", line 443, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/home/chris/.pyenv/versions/3.11.4/lib/python3.11/site-packages/dagster/_core/execution/plan/compute_generator.py", line 136, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/home/chris/.pyenv/versions/3.11.4/lib/python3.11/site-packages/dagster/_core/execution/plan/compute_generator.py", line 130, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
                                                                    ^^^^^^^^^^^^^^^^^^
  File "/home/chris/code/affinitypropagation/valuationhub/valuationhub/assets.py", line 81, in upload_info
    df = pd.read_csv(
         ^^^^^^^^^^^^
  File "/home/chris/.pyenv/versions/3.11.4/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chris/.pyenv/versions/3.11.4/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chris/.pyenv/versions/3.11.4/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chris/.pyenv/versions/3.11.4/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/chris/.pyenv/versions/3.11.4/lib/python3.11/site-packages/pandas/io/common.py", line 859, in get_handle
    handle = open(
             ^^^^^
[0m
